web:
  build: .
  links:
   - db
   - redis
  ports:
   - "5000:5000"
  environment:
    DATABASE_URL: postgres://postgres:postgres@db:5432/toshi_development
    REDIS_URL: redis://redis/0
    RACK_ENV: development
db:
  image: "postgres:9.3"
redis:
  image: "redis:2.8"
